### ISSUE TITLE
Showing total time as less than 1 minute despite having multiple weeks of playback

### ISSUE THREAD

**Issue by Simsala91** [jellyfin/jellyfin-plugin-playbackreporting#119]
My playback reporting is showing <1 Minute for some users, even though they have a lot of activity on the server. This was not the case when I last looked, might only have occured with the latest update to 10.11.2

As far as I remember, this used to have worked fine with 10.10.7

<img width="2839" height="255" alt="Image" src="https://github.com/user-attachments/assets/99b29589-7934-4a04-9fba-561db84d4b94" />

For one user this only happens if I select timeframe "All", For another this always happens.
Might be some playback entry with a high negative value for some reason?

**Comment by wafflesLL** [comment]
I fixed this issue i think in this pull request.
I think the unix time measurement was causing an integer overflow, so I just made it a long instead of an int, which should hypothetically fix it. Might have to change to an unsigned long to get the full time measurement:
[My pull request](https://github.com/jellyfin/jellyfin-plugin-playbackreporting/pull/120)

**Comment by l0stpt** [comment]
Same thing happening to me.

**Comment by StNimmerlein** [comment]
I just updated to Jellyfin 12.0 and Playback Reporting 19 which should include this fix. However, I still see "< 1 minute" for my main user when selecting more than one week.
