### ISSUE TITLE
Errant duplicate music playbacks with very long playback times added most days

### ISSUE THREAD

**Issue by holotone** [jellyfin/jellyfin-plugin-playbackreporting#81]
When I log in most days to see Playback Reporting I switch to "Play Time" view and see that on a random day my admin user has FAR more minutes than they should

![image](https://github.com/jellyfin/jellyfin-plugin-playbackreporting/assets/114688120/e6b31623-5653-4541-9a29-9f83e5abd925)

If I scroll down the list I'll see a duplicate entry for a song I listened to showing its playback time in the hundreds of minutes:

![image](https://github.com/jellyfin/jellyfin-plugin-playbackreporting/assets/114688120/ab59980a-6225-4f9c-9ce8-12a45e350061)

If I delete the errant entry it goes away and Playback Reporting behaves as expected until the next day when a new errant duplicate entry for a different song that I listened to is added.

Until I delete the errant entry I cannot see everyone else's relative playback times because they get scaled to be too small.

Thanks!

**Comment by wfrank21** [comment]
Having the same issue here with audio book playback time showing more than five times the amount an episode is.
Episiode is 60min long, playback shows 6-7 hours playback on this one file by one user, where only 20min were actually listened

**Comment by holotone** [comment]
Its probably worth noting that for me the file with the errant playback time is random and is usually something I listened to a few days prior. It will report correctly for a couple days then *poof*, it's wrong out of nowhere.

**Comment by wfrank21** [comment]
I need to watch this closely, I only started using this plugin yesterday.

**Comment by holotone** [comment]
I just noticed that the songs that are getting errantly duplicated with hundreds of hours on previous days are songs that I listened to for a second time, in this case this morning just before I checked the Playback Report.

**Comment by crobibero** [comment]
Should be fixed by plugin v15

**Comment by holotone** [comment]
> Should be fixed by plugin v15

Right on, thanks!

**Comment by holotone** [comment]
Just a quick update that this issue is definitely not fixed, and it seems to have added a new eccentricity. Instead of just misreporting one track's time to be much longer than it was (ie 100s of hours in playback time) now it will sometimes list a single track as being played for 0:00 hundreds / thousands of times in a row. Both of these issues make it difficult to see any other activity in the Playback Reporting screen because it throws the scale off for everyone else.

Thanks!
